spring:
  liquibase:
    change-log: classpath:migrations/db.changelog-master.yaml
  application:
    name: DGroup
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true